# Generated by Django 5.1.3 on 2025-05-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='generated_meme',
            field=models.ImageField(blank=True, null=True, upload_to='memes/generated/'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(upload_to='memes/originals/'),
        ),
    ]
