# Generated by Django 5.1.3 on 2025-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_meme_bottom_text_remove_meme_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='generated_meme',
        ),
        migrations.AddField(
            model_name='meme',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memes/originals/'),
        ),
        migrations.AddField(
            model_name='meme',
            name='top_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
